Repository geli-lms/geli, pull requests merged in 2018-04, with the labels that each got.

#596 Bugfix/#595 fix download course after media
  api/src/controllers/DownloadController.ts
  api/src/models/units/CodeKataUnit.ts
  api/src/models/units/FileUnit.ts
  api/src/models/units/FreeTextUnit.ts
  api/src/models/units/TaskUnit.ts
  api/src/models/units/Unit.ts
  app/webFrontend/src/app/course/course-detail/download-course-dialog/download-course-dialog.component.ts
  app/webFrontend/src/app/course/course-detail/download-course-dialog/downloadCheckBoxes/upload-unit-checkbox.component.ts
Labels: bug

#636 Bugfix/#583 Fix running-locally.md link to docker-compose.yml
  docs/development/running-locally.md
Labels: trivial

#552 Annotate tag so that it gets pushed by --follow-tags (to gh page)
  .travis/apidoc.sh
Labels: bug

#648 Send notification about deleted course before deleting course
  app/webFrontend/src/app/course/course-edit/general-tab/general-tab.component.ts
Labels: blocked

#678 Fix progress save and populate
  api/src/models/units/Unit.ts
  app/webFrontend/src/app/about/general-info/contributor.model.ts
  app/webFrontend/src/app/about/general-info/contributors.ts
  app/webFrontend/src/app/models/progress/CodeKataUnitProgress.ts
  app/webFrontend/src/app/models/progress/TaskUnitProgress.ts
Labels: api, bug

#664 Bugfix/#654 wasteful course data fix
  CHANGELOG.md
  api/fixtures/courses/Access-key-test.json
  api/src/controllers/CourseController.ts
  api/src/models/Course.ts
  api/src/models/Lecture.ts
  api/src/utilities/ExtractMongoId.ts
  api/test/integration/course.ts
  api/test/unit/utilities.ts
  app/webFrontend/src/app/course/course-container/course-container.component.ts
  app/webFrontend/src/app/course/course-detail/course-detail.component.ts
  app/webFrontend/src/app/course/course-edit/course-manage-content/course-manage-content.component.ts
  app/webFrontend/src/app/course/course-edit/course-media/course-media.component.ts
  app/webFrontend/src/app/course/course-edit/general-tab/general-tab.component.ts
  app/webFrontend/src/app/course/course-edit/members/members.component.ts
  app/webFrontend/src/app/course/course-edit/teachers/teachers.component.ts
  app/webFrontend/src/app/course/course.component.html
  app/webFrontend/src/app/course/course.component.ts
  app/webFrontend/src/app/shared/services/data.service.ts
  app/webFrontend/src/app/start/dashboard/dashboard-base-component.ts
  app/webFrontend/src/app/start/dashboard/dashboard-student/dashboard-student.component.ts
  app/webFrontend/src/app/start/dashboard/dashboard-teacher/dashboard-teacher.component.ts
  app/webFrontend/src/app/start/dashboard/dashboard.component.ts
  shared/models/ICourse.ts
  shared/models/ICourseDashboard.ts
  shared/models/ICourseView.ts
Labels: api, bug, enhancement, refactoring, web-frontend

#667 Bugfix/#659 empty download course
  CHANGELOG.md
  app/webFrontend/src/app/course/course-detail/download-course-dialog/download-course-dialog.component.html
  app/webFrontend/src/app/course/course-detail/download-course-dialog/download-course-dialog.component.ts
  app/webFrontend/src/app/course/course-detail/download-course-dialog/downloadCheckBoxes/lecture-checkbox.component.html
Labels: bug, web-frontend
